#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <math.h>
#include <assert.h>

float *rand_num_gen(int num_elements)
{
    float *rand_nums = (float *)malloc(sizeof(float) * num_elements);
    assert(rand_nums != NULL);
    for (int i = 0; i < num_elements; i++)
    {
        rand_nums[i] = rand() / (float)RAND_MAX;
    }
    return rand_nums;
}

int main(int argc, char **argv)
{

    int nproc, rank;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &nproc);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    int num_elements_per_proc = atoi(argv[1]);
    srand(1234 * (rank + 1));
    float *rand_nums = rand_num_gen(num_elements_per_proc);

    printf("Numbers generated by process %d: ", rank);
    for (int i = 0; i < num_elements_per_proc; i++)
    {
        printf("%.3f ", rand_nums[i]);
    }
    printf("\n");

    float local_sum = 0.0;
    for (int i = 0; i < num_elements_per_proc; i++)
    {
        local_sum += rand_nums[i];
    }
    printf("Local sum of process %d: %.3f\n", rank, local_sum);

    float global_sum;
    MPI_Allreduce(&local_sum, &global_sum, 1, MPI_FLOAT, MPI_SUM, MPI_COMM_WORLD);

    float global_mean = global_sum / (num_elements_per_proc * nproc);

    float local_sq_diff_sum = 0.0;
    for (int i = 0; i < num_elements_per_proc; i++)
    {
        local_sq_diff_sum += (rand_nums[i] - global_mean) * (rand_nums[i] - global_mean);
    }
    float global_sq_diff_sum;
    MPI_Reduce(&local_sq_diff_sum, &global_sq_diff_sum, 1, MPI_FLOAT, MPI_SUM, 0, MPI_COMM_WORLD);

    if (rank == 0)
    {
        float stddev = sqrt(global_sq_diff_sum / (num_elements_per_proc * nproc));
        printf("Standard Deviation: %.3f\n", stddev);
    }

    free(rand_nums);
    MPI_Finalize();
    return 0;
}
